title: OK Page
author:
  name: otokal
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

inputs:
  - name: key1
    type: textbox
  - name: key2
    type: textbox
  - name: key3
    type: textbox
  - name: key4
    type: textbox
  - name: key5
    type: textbox
  - name: key6
    type: textbox
  - name: key7
    type: textbox
  - name: key8
    type: textbox
  - name: key9
    type: textbox
  - name: key10
    type: textbox
###############################
actions:
  - type: submit
    label: Generate Password
    script: |
      var keys = [
        "{{inputs.key1}}",
        "{{inputs.key2}}",
        "{{inputs.key3}}",
        "{{inputs.key4}}",
        "{{inputs.key5}}",
        "{{inputs.key6}}",
        "{{inputs.key7}}",
        "{{inputs.key8}}",
        "{{inputs.key9}}",
        "{{inputs.key10}}",
      ];
################################
      var passwords = generatePasswords(keys);
      setOutput("password1", passwords[0]);
      setOutput("password2", passwords[1]);
      setOutput("password3", passwords[2]);
      setOutput("password4", passwords[3]);
      setOutput("password5", passwords[4]);
      setOutput("password6", passwords[5]);
      setOutput("password7", passwords[6]);
      setOutput("password8", passwords[7]);
      setOutput("password9", passwords[8]);
      setOutput("password10", passwords[9]);
##############################
output:
  - type: textbox
    name: password1
    label: Generated Password for Key 1
  - type: textbox
    name: password2
    label: Generated Password for Key 2
  - type: textbox
    name: password3
    label: Generated Password for Key 3
  - type: textbox
    name: password1
    label: Generated Password for Key 4
  - type: textbox
    name: password2
    label: Generated Password for Key 5
  - type: textbox
    name: password3
    label: Generated Password for Key 6
  - type: textbox
    name: password1
    label: Generated Password for Key 7
  - type: textbox
    name: password2
    label: Generated Password for Key 8
  - type: textbox
    name: password3
    label: Generated Password for Key 9
  - type: textbox
    name: password3
    label: Generated Password for Key 10

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: dark

  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  #social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
