---
title: Password Generator
inputs:
  - name: answer 1
    type: textbox
  - name: answer 2
    type: textbox
  - name: answer 3
    type: textbox
  - name: answer 4
    type: textbox
  - name: answer 5
    type: textbox
  - name: answer 6
    type: textbox
  - name: answer 7
    type: textbox
  - name: answer 8
    type: textbox
  - name: answer 9
    type: textbox
  - name: answer 10
    type: textbox
###############################
actions:
  - type: submit
    label: Generate Password
    script: |
      var keys = [
        "{{inputs.key1}}",
        "{{inputs.key2}}",
        "{{inputs.key3}}",
        "{{inputs.key4}}",
        "{{inputs.key5}}",
        "{{inputs.key6}}",
        "{{inputs.key7}}",
        "{{inputs.key8}}",
        "{{inputs.key9}}",
        "{{inputs.key10}}",
      ];
################################
      var passwords = generatePasswords(keys);
      setOutput("password1", passwords[0]);
      setOutput("password2", passwords[1]);
      setOutput("password3", passwords[2]);
      setOutput("password4", passwords[3]);
      setOutput("password5", passwords[4]);
      setOutput("password6", passwords[5]);
      setOutput("password7", passwords[6]);
      setOutput("password8", passwords[7]);
      setOutput("password9", passwords[8]);
      setOutput("password10", passwords[9]);
##############################
output:
  - type: textbox
    name: password1
    label: Generated Password for Key 1
  - type: textbox
    name: password2
    label: Generated Password for Key 2
  - type: textbox
    name: password3
    label: Generated Password for Key 3
  - type: textbox
    name: password1
    label: Generated Password for Key 4
  - type: textbox
    name: password2
    label: Generated Password for Key 5
  - type: textbox
    name: password3
    label: Generated Password for Key 6
  - type: textbox
    name: password1
    label: Generated Password for Key 7
  - type: textbox
    name: password2
    label: Generated Password for Key 8
  - type: textbox
    name: password3
    label: Generated Password for Key 9
  - type: textbox
    name: password3
    label: Generated Password for Key 10
